// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"GlobalLayout":{"id":"GlobalLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"GlobalLayout","isLayout":true},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"GlobalLayout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/snow/Desktop/WorkShip/AI-Component/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.5_@swc+helpers@0.5.15_@types+node@20.5.1_@types+react@18.3_134955f638bd903cafd610c6d59e423b/node_modules/dumi/dist/client/pages/404.js')),
'GlobalLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi-theme-antd-laf__dist__layouts__GlobalLayout" */'/Users/snow/Desktop/WorkShip/AI-Component/node_modules/dumi-theme-antd-laf/dist/layouts/GlobalLayout.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/snow/Desktop/WorkShip/AI-Component/.dumi/tmp/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi-theme-antd-laf__dist__layouts__DocLayout__index" */'/Users/snow/Desktop/WorkShip/AI-Component/node_modules/dumi-theme-antd-laf/dist/layouts/DocLayout/index.js')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/snow/Desktop/WorkShip/AI-Component/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.5_@swc+helpers@0.5.15_@types+node@20.5.1_@types+react@18.3_134955f638bd903cafd610c6d59e423b/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
