// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/snow/Desktop/WorkShip/AI-Component/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.5_@swc+helpers@0.5.15_@types+node@20.5.1_@types+react@18.3_134955f638bd903cafd610c6d59e423b/node_modules/dumi/theme-default/slots/HeaderExtra/index.js';
