// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/snow/Desktop/WorkShip/AI-Component/node_modules/dumi-theme-antd-laf/dist/slots/Sidebar/index.js';
